//============ Request api for server ==========================//

export const REQUEST_API_QUESTIONS = 'REQUEST_API_QUESTIONS'
export const REQUEST_API_LISTLESSON = 'REQUEST_API_LISTLESSON'
export const REQUEST_API_CATEROGY = 'REQUEST_API_CATEROGY'

//============ Request api action of client =========================// 

export const ACTION_ADD_QUESTION = 'ACTION_ADD_QUESTION'
export const ACTION_DELETE_QUESTION = 'ACTION_DELETE_QUESTION'
export const ACTION_EDIT_QUESTION = 'ACTION_EDIT_QUESTION'

export const ACTION_ADD_LESSON = 'ACTION_ADD_LESSON'
export const ACTION_DELETE_LESSON = 'ACTION_EDIT_LESSON'
export const ACTION_EIDT_LESSON = 'ACTION_EIDT_LESSON'

export const ACTION_ADD_CATERORY = 'ACTION_ADD_CATERORY'
export const ACTION_DELETE_CATEGORY = 'ACTION_DELETE_CATEGORY'
export const ACTION_EIDT_CATEGORY = 'ACTION_EIDT_CATEGORY'
